In [1]:
import pandas as pd

# Load your CSV file
# Error: The path string has backslashes that are being interpreted as escape characters
# Fix: Either use raw strings, double backslashes, or forward slashes
# Option 1: Use raw string
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\data.csv')  # r prefix makes it a raw string

# Option 2: Use double backslashes
# df = pd.read_csv('C:\\Users\\HP\\OneDrive\\Desktop')  

# Option 3: Use forward slashes (works on Windows too)
# df = pd.read_csv('C:/Users/HP/OneDrive/Desktop')  

# Note: You should also include the actual CSV filename in the path
# For example: r'C:\Users\HP\OneDrive\Desktop\your_file.csv'

# Display the first few rows
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [2]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [3]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [4]:
df.shape

(32, 5)

In [5]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [1]:
df.drop('Ticket', axis=1, inplace=True

_IncompleteInputError: incomplete input (3969855982.py, line 1)

In [2]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2025.7.14)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.amazon.in/product-reviews/B0BGSYMQD5/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews")

reviews = driver.find_elements(By.CLASS_NAME, "review-text")
for r in reviews:
    print(r.text)

driver.quit()

ModuleNotFoundError: No module named 'selenium'

In [5]:
!pip install selenium

# Then import and use selenium
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.amazon.in/product-reviews/B0BGSYMQD5/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews")

reviews = driver.find_elements(By.CLASS_NAME, "review-text")
for r in reviews:
    print(r.text)

driver.quit()

Collecting selenium
  Downloading selenium-4.34.2-py3-none-any.whl.metadata (7.5 kB)
Collecting urllib3~=2.5.0 (from urllib3[socks]~=2.5.0->selenium)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting trio~=0.30.0 (from selenium)
  Downloading trio-0.30.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.6.15 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2025.7.14)
Collecting typing_extensions~=4.14.0 (from selenium)
  Downloading typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: websocket-client~=1.8.0 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.30.0->selenium) (24.3.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.30.0->selenium) (3.7)
Collecting outcome (from trio~=0.30.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.30.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.30.0->selenium) (1.17.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.12.2->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]~=2.5.0->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.30.0->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)
Downloading selenium-4.34.2-py3-none-any.whl (9.4 MB)
   ---------------------------------------- 0.0/9.4 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.4 MB 10.4 MB/s eta 0:00:01
   --------------- ------------------------ 3.7/9.4 MB 10.8 MB/s eta 0:00:01
   ------------------------ --------------- 5.8/9.4 MB 10.7 MB/s eta 0:00:01
   ------------------------------- -------- 7.3/9.4 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 9.4/9.4 MB 9.9 MB/s eta 0:00:00
Downloading trio-0.30.0-py3-none-any.whl (499 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading typing_extensions-4.14.1-py3-none-any.whl (43 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, typing_extensions, outcome, trio, trio-websocket, selenium

  Attempting uninstall: urllib3

    Found existing installation: urllib3 2.3.0

    Uninstalling urllib3-2.3.0:

      Successfully uninstalled urllib3-2.3.0

   ----- ---------------------------------- 1/7 [urllib3]
  Attempting uninstall: typing_extensions
   ----- ---------------------------------- 1/7 [urllib3]
    Found existing installation: typing_extensions 4.12.2
   ----- ---------------------------------- 1/7 [urllib3]
    Uninstalling typing_extensions-4.12.2:
   ----- ---------------------------------- 1/7 [urllib3]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
   ----------- ---------------------------- 2/7 [typing_extensions]
      Successfully uninstalled typing_extensions-4.12.2
   ----------- ---------------------------- 2/7 [typing_extensions]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------------- 7/7 [selenium]

Successfully installed outcome-1.3.0.post0 selenium-4.34.2 trio-0.30.0 trio-websocket-0.12.2 typing_extensions-4.14.1 urllib3-2.5.0 wsproto-1.2.0

In [9]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

driver = webdriver.Chrome(executable_path='path/to/chromedriver')
driver.get("https://www.amazon.in/product-reviews/B07X1KT6BY")

reviews = driver.find_elements(By.CSS_SELECTOR, "[data-hook='review']")
data = []

for r in reviews:
    title = r.find_element(By.CSS_SELECTOR, "[data-hook='review-title']").text
    rating = r.find_element(By.CSS_SELECTOR, "[data-hook='review-star-rating']").text
    body = r.find_element(By.CSS_SELECTOR, "[data-hook='review-body']").text
    data.append({'Title': title, 'Rating': rating, 'Review': body})

df = pd.DataFrame(data)
df.to_csv('amazon_reviews.csv', index=False)
driver.quit()

TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

In [10]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import pandas as pd

# Create a Service object with the path to chromedriver
service = Service(executable_path='path/to/chromedriver')
# Pass the service object to the webdriver.Chrome constructor
driver = webdriver.Chrome(service=service)
driver.get("https://www.amazon.in/product-reviews/B07X1KT6BY")

reviews = driver.find_elements(By.CSS_SELECTOR, "[data-hook='review']")
data = []

for r in reviews:
    title = r.find_element(By.CSS_SELECTOR, "[data-hook='review-title']").text
    rating = r.find_element(By.CSS_SELECTOR, "[data-hook='review-star-rating']").text
    body = r.find_element(By.CSS_SELECTOR, "[data-hook='review-body']").text
    data.append({'Title': title, 'Rating': rating, 'Review': body})

df = pd.DataFrame(data)
df.to_csv('amazon_reviews.csv', index=False)
driver.quit()

NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

In [11]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2025.7.14)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Step 1: Set headers to mimic Chrome browser
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/115 Safari/537.36',
    'Accept-Language': 'en-US,en;q=0.9'
}

# Step 2: Define the Amazon review page URL
url = "https://www.amazon.in/ZEBRONICS-Zeb-Blitz-Headphone-Software-Simulated/dp/B09P1KK9K1/?_encoding=UTF8&pd_rd_w=2NhnC&content-id=amzn1.sym.3eb27980-84ee-4cfe-bafb-8634b1863e1c%3Aamzn1.symc.36bd837a-d66d-47d1-8457-ffe9a9f3ddab&pf_rd_p=3eb27980-84ee-4cfe-bafb-8634b1863e1c&pf_rd_r=MY7E30BK7F0QABSHDEQW&pd_rd_wg=mYIvN&pd_rd_r=e1518b04-7ec7-401b-beec-f705c04dd32d&ref_=pd_hp_d_btf_ci_mcx_mr_hp_atf_m&th=1"

# Step 3: Send request and parse HTML
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

# Step 4: Extract review blocks
review_blocks = soup.find_all('div', {'data-hook': 'review'})

# Step 5: Extract review details
reviews = []
for block in review_blocks:
    title = block.find('a', {'data-hook': 'review-title'})
    rating = block.find('i', {'data-hook': 'review-star-rating'})
    body = block.find('span', {'data-hook': 'review-body'})
    
    reviews.append({
        'Title': title.text.strip() if title else '',
        'Rating': rating.text.strip() if rating else '',
        'Review': body.text.strip() if body else ''
    })

# Step 6: Save to CSV
df = pd.DataFrame(reviews)
df.to_csv('amazon_reviews.csv', index=False)
df.head()

Empty DataFrame
Columns: []
Index: []

In [14]:
print(response.status_code)          # Should be 200
print(len(response.text))            # Should be >10,000 ideally

200
2465755

In [17]:

import pandas as pd
import json
from pandas import json_normalize


with open('Cell_Phones_and_Accessories_5.json', 'r', encoding='utf-8') as file:
    data = Cell_Phones_and_Accessories_5.load(file)


df = json_normalize(data) 
print("✅ Loaded and normalized data:")
print(df.head())

# Step 4: Inspect and clean the data

# Rename columns for clarity (update based on your JSON structure)
df.rename(columns={
    'review_title': 'Title',
    'review_rating': 'Rating',
    'review_text': 'Review',
    'review_date': 'Date'
}, inplace=True)

# Strip whitespace
df['Review'] = df['Review'].astype(str).str.strip()
df['Title'] = df['Title'].astype(str).str.strip()

# Remove missing values
df.dropna(subset=['Review', 'Rating'], inplace=True)

# Optional: Filter out empty strings or invalid ratings
df = df[df['Rating'].astype(str).str.strip() != '']
df = df[df['Review'].astype(str).str.strip() != '']

# Step 5: Save cleaned data to CSV
df.to_csv('cleaned_reviews.csv', index=False)

print(f"📁 Saved {len(df)} cleaned reviews to 'cleaned_amazon_reviews.csv'")

FileNotFoundError: [Errno 2] No such file or directory: 'Cell_Phones_and_Accessories_5.json'